package io.swagger.petstore.asserts;

import io.swagger.petstore.entities.Tag;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Tag} specific assertions - Generated by CustomAssertionGenerator.
 */
public class TagAssert extends AbstractAssert<TagAssert, Tag> {

    /**
     * Creates a new <code>{@link TagAssert}</code> to make assertions on actual Tag.
     *
     * @param actual the Tag we want to make assertions on.
     */
    private TagAssert(Tag actual) {
        super(actual, TagAssert.class);
    }

    /**
     * An entry point for TagAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myTag)</code> and get specific assertion with code completion.
     *
     * @param actual the Tag we want to make assertions on.
     * @return a new <code>{@link TagAssert}</code>
     */
    public static TagAssert assertThat(Tag actual) {
        return new TagAssert(actual);
    }

    /**
     * Verifies that the actual Tag's id is equal to the given one.
     *
     * @param id the given id to compare the actual Tag's id to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Tag's id is not equal to the given one.
     */
    public TagAssert hasId(int id) {
        // check that actual Tag we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualId = actual.getId();
        if (actualId != id) {
            failWithMessage(assertjErrorMessage, actual, id, actualId);
        }

        // return the current assertion for method chaining
        return this;
    }

    /**
     * Verifies that the actual Tag's name is equal to the given one.
     *
     * @param name the given name to compare the actual Tag's name to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Tag's name is not equal to the given one.
     */
    public TagAssert hasName(String name) {
        // check that actual Tag we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        String actualName = actual.getName();
        if (!Objects.areEqual(actualName, name)) {
            failWithMessage(assertjErrorMessage, actual, name, actualName);
        }

        // return the current assertion for method chaining
        return this;
    }

}
